---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)



```

# my_fun

```{r function-get_info_data}
#' get_info_data Title
#'
#' @param data a dataframe
#'
#' @return two messages
#' @export 
#'
#' @examples

get_info_data <- function(data){

 
if (!is.data.frame(data)){stop(paste0(data, " is not a dataframe"))}  
  
dimension <- c(ncol(data), nrow(data))
print(dimension)

names <- colnames(data)
print(names)
}

```

```{r examples-get_info_data}
get_info_data(iris)
```

```{r tests-my_fun}
test_that("get_info_data works", {

  expect_error(get_info_data("mydata"), "mydata is not a dataframe") 
})

```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", vignette_name = "Minimal")
```
