# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

#' get_info_data Title
#'
#' @param data a dataframe
#'
#' @return two messages
#' @export 
#'
#' @examples

#' get_info_data(iris)
get_info_data <- function(data){

 
if (!is.data.frame(data)){stop(paste0(data, " is not a dataframe"))}  
  
dimension <- c(ncol(data), nrow(data))
print(dimension)

names <- colnames(data)
print(names)
}

